"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowRight,BarChart3,Check,ChevronLeft,ChevronRight,ClipboardCheck,Compass,Download,RotateCcw,Sparkles,Target} from "lucide-react";
type Rating={implementation?:number|string;priority?:number};
const D=[
 {id:"change",phase:"ACTIVATE",name:"Change Agents",c:"#00a7c7",desc:"Empower people across the community to see themselves as change-makers.",q:"Whose voices are meaningfully shaping the work—and whose voices need to be more fully included?",items:["A wide range of stakeholders have meaningful opportunities to influence decisions related to the transformation.","Roles, responsibilities, and decision-making authority are clearly defined and understood.","Team roles align with individuals' strengths, expertise, identities, and lived experiences.","Leadership development, coaching, mentoring, and meaningful leadership opportunities are available across roles."]},
 {id:"purpose",phase:"ACTIVATE",name:"Shared Purpose",c:"#1687c9",desc:"Develop a common understanding of the vision, values, principles, and goals for transforming learning.",q:"What is our vision for student success—and where are there different understandings?",items:["The organization systematically listens to stakeholder passions, concerns, experiences, and priorities, especially those historically marginalized.","The problem or opportunity driving transformation has been examined beyond surface-level symptoms using root-cause analysis and evidence.","Staff, students, families, and other stakeholders have participated in shaping the vision for student learning and success.","People across roles can clearly explain the shared purpose and how it connects to student learning and success."]},
 {id:"inclusive",phase:"BUILD",name:"Inclusive Environment",c:"#7856b8",desc:"Strengthen the trust and relationships that create an environment supportive of change.",q:"Where are diverse voices included—and what structures help people safely contribute different perspectives?",items:["Decision-making teams reflect community diversity and meaningfully include people historically marginalized by current systems.","Individuals regularly raise concerns, challenge inequities, offer different perspectives, and ask for help.","Teams use shared norms, protocols, and routines for honest dialogue, collaboration, feedback, and learning through conflict.","Communication is accessible, inclusive, and reciprocal: teams respond or adapt and communicate outcomes back to stakeholders."]},
 {id:"learning",phase:"BUILD",name:"ReBuild Learning",c:"#a34b97",desc:"Test approaches that bring the community's shared purpose to life in learning experiences.",q:"What experience do we have testing new approaches—and what would make experimentation more possible?",items:["A clear transformation priority has been identified through collaborative examination of student experience, equity, implementation, and outcome data.","Cross-role teams have the authority, time, support, and resources needed to design and test new approaches.","Teams use a structured improvement cycle to establish learning questions, gather evidence, reflect, and refine their work.","Learning experiences reflect the shared vision for student success, including academic learning and broader competencies.","Setbacks, disagreement, pushback, and unsuccessful attempts are openly examined and used for learning and improvement."]},
 {id:"culture",phase:"EMBED",name:"Culture of Innovation",c:"#df6536",desc:"Build a community-wide culture of inquiry, shared ownership, and continuous improvement.",q:"What systems preserve and spread learning—and what would happen if a key leader left tomorrow?",items:["The organization regularly identifies, documents, and communicates progress, challenges, and learning.","Contributions from staff, students, families, teams, and partners are recognized in inclusive and culturally responsive ways.","Knowledge, responsibility, and decision-making are distributed across people and teams rather than concentrated in one leader.","New community members are introduced to the transformation purpose, shared commitments, and how the work appears in practice."]},
 {id:"infrastructure",phase:"EMBED",name:"Aligned Infrastructure",c:"#e99c28",desc:"Shift systems and structures to align with the shared purpose and support learning over compliance.",q:"Which systems already support transformation—and which policies or routines may create barriers?",items:["Time, staffing, funding, and structures align to support collaboration, professional learning, implementation, and improvement.","Hiring, staffing, leadership roles, and professional learning reflect the values and capabilities needed to advance transformation.","Policies, routines, schedules, and processes are reviewed and redesigned when they conflict with the transformation purpose.","Leaders model listening, shared decision-making, inquiry, reflection, and responsiveness to feedback."]}
];
const ITEMS=D.flatMap((d,di)=>d.items.map((text,i)=>({...d,text,n:D.slice(0,di).reduce((a,x)=>a+x.items.length,0)+i+1})));
export default function Home(){
 const [view,setView]=useState<"home"|"assessment"|"profile">("home"),[ratings,setRatings]=useState<Record<number,Rating>>({}),[step,setStep]=useState(0),[ready,setReady]=useState(false);
 useEffect(()=>{try{const x=localStorage.getItem("leap-readiness");if(x)setRatings(JSON.parse(x))}finally{setReady(true)}},[]);useEffect(()=>{if(ready)localStorage.setItem("leap-readiness",JSON.stringify(ratings))},[ratings,ready]);
 const completed=Object.values(ratings).filter(x=>x.implementation!==undefined&&x.priority).length;
 const scores=useMemo(()=>D.map(d=>{const rs=ITEMS.filter(x=>x.id===d.id).map(x=>ratings[x.n]).filter(Boolean);const nums=rs.map(x=>x.implementation).filter((x):x is number=>typeof x==="number");return{...d,imp:nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0,pri:rs.filter(x=>x.priority).length?rs.reduce((a,x)=>a+(x.priority||0),0)/rs.filter(x=>x.priority).length:0}}),[ratings]);
 const focus=[...scores].filter(x=>x.imp&&x.pri).sort((a,b)=>(b.pri-b.imp)-(a.pri-a.imp))[0],cur=D[step];
 const rate=(n:number,k:keyof Rating,v:number|string)=>setRatings(r=>({...r,[n]:{...r[n],[k]:v}}));
 return <main><header><div className="brand"><b>L</b><span>LEAP <strong>Transformation Navigator</strong></span></div><nav>{[["home","Home"],["assessment","Assessment"],["profile","My profile"]].map(x=><button className={view===x[0]?"active":""} onClick={()=>setView(x[0] as typeof view)} key={x[0]}>{x[1]}</button>)}</nav></header>
 {view==="home"&&<><section className="hero"><div><p className="eyebrow">A DEVELOPMENTAL TOOL FOR SCHOOL & DISTRICT TEAMS</p><h1>See what is ready.<em>Shape what comes next.</em></h1><p className="lede">Explore the strengths, conditions, and supports that can enable equitable and sustainable transformation—without reducing readiness to a yes or no.</p><button className="primary" onClick={()=>setView("assessment")}>{completed?"Continue your assessment":"Begin the assessment"}<ArrowRight/></button><small><Check/> Progress saves automatically on this device</small></div><div className="orbit"><div className="core"><Compass/><b>Transform</b><span>learning</span></div>{D.map((d,i)=><div className={`node n${i}`} style={{"--c":d.c} as React.CSSProperties} key={d.id}><small>{d.phase}</small>{d.name}</div>)}</div></section>
 <section className="intro"><div><span>01</span><h2>A fuller picture of readiness</h2></div><p>The assessment looks across relational, cultural, instructional, leadership, and structural conditions. Complete it individually or use it to guide a facilitated team conversation.</p></section><section className="phases">{["ACTIVATE","BUILD","EMBED"].map((p,i)=><article key={p}><h3><span>0{i+1}</span>{p}</h3>{D.filter(d=>d.phase===p).map(d=><div style={{borderColor:d.c}} key={d.id}><b>{d.name}</b><p>{d.desc}</p></div>)}</article>)}</section><section className="how"><div><p className="eyebrow">HOW IT WORKS</p><h2>From reflection to a focused next move.</h2></div><div className="steps">{[[ClipboardCheck,"Assess","Rate 25 conditions for implementation and priority."],[BarChart3,"Explore","See a six-domain profile and the gaps that merit attention."],[Target,"Focus","Choose a condition for your team's next learning cycle."]].map(([I,t,p],i)=>{const Icon=I as typeof Target;return <article key={String(t)}><span>0{i+1}</span><Icon/><h3>{String(t)}</h3><p>{String(p)}</p></article>})}</div></section></>}
 {view==="assessment"&&<section className="workspace"><aside><p className="eyebrow">YOUR ASSESSMENT</p><div className="count"><b>{completed}</b><span>of 25 complete</span></div><i className="track"><em style={{width:`${completed*4}%`}}/></i>{D.map((d,i)=><button className={step===i?"sel":""} onClick={()=>setStep(i)} key={d.id}><span style={{background:d.c}}>{i+1}</span><small>{d.phase}<b>{d.name}</b></small>{ITEMS.filter(x=>x.id===d.id).every(x=>ratings[x.n]?.implementation!==undefined&&ratings[x.n]?.priority)&&<Check/>}</button>)}</aside><div className="assessment"><div className="ahead"><div><p className="eyebrow" style={{color:cur.c}}>{cur.phase} · DOMAIN {step+1} OF 6</p><h1>{cur.name}</h1><p>{cur.desc}</p></div><div className="legend"><b>Implementation</b><span>1 Beginning · 2 Developing · 3 Ready · 4 Sustaining · NE</span><b>Priority</b><span>1 Not now · 2 Low · 3 Moderate · 4 High</span></div></div><div className="items">{ITEMS.filter(x=>x.id===cur.id).map(x=><article className="item" key={x.n}><span className="num">{String(x.n).padStart(2,"0")}</span><p>{x.text}</p><fieldset><legend>Implementation</legend>{[1,2,3,4,"NE"].map(v=><button className={ratings[x.n]?.implementation===v?"chosen":""} onClick={()=>rate(x.n,"implementation",v)} key={v}>{v}</button>)}</fieldset><fieldset><legend>Priority</legend>{[1,2,3,4].map(v=><button className={ratings[x.n]?.priority===v?"chosen":""} onClick={()=>rate(x.n,"priority",v)} key={v}>{v}</button>)}</fieldset></article>)}</div><div className="reflect"><Sparkles/><p><b>Pause and reflect</b>{cur.q}</p></div><div className="pager"><button disabled={!step} onClick={()=>setStep(x=>x-1)}><ChevronLeft/>Previous</button>{step<5?<button className="primary" onClick={()=>setStep(x=>x+1)}>Next domain<ChevronRight/></button>:<button className="primary" onClick={()=>setView("profile")}>View profile<Sparkles/></button>}</div></div></section>}
 {view==="profile"&&<section className="results"><div className="rhead"><div><p className="eyebrow">YOUR TRANSFORMATION READINESS PROFILE</p><h1>What your team can build from.</h1><p>{completed===25?"All 25 conditions are reflected below.":`${completed} of 25 conditions are complete. Finish the assessment for the clearest profile.`}</p></div><div><button onClick={()=>setView("assessment")}><ClipboardCheck/>Finish assessment</button><button onClick={()=>window.print()}><Download/>Save / print</button></div></div>{focus&&<article className="focus"><span><Target/> RECOMMENDED FOCUS</span><h2>{focus.name}</h2><p>This area combines high current priority with room to strengthen implementation. Use it as a starting point for team sensemaking—not an automatic prescription.</p><button onClick={()=>{setStep(D.findIndex(d=>d.id===focus.id));setView("assessment")}}>Explore conditions<ArrowRight/></button></article>}<div className="scores">{scores.map(s=><article style={{"--c":s.c} as React.CSSProperties} key={s.id}><small>{s.phase}</small><h3>{s.name}</h3>{[["Implementation",s.imp],["Priority",s.pri]].map(([t,v])=><div className="bar" key={String(t)}><label>{t}<b>{Number(v)?Number(v).toFixed(1):"—"}</b></label><i><em style={{width:`${Number(v)/4*100}%`}}/></i></div>)}</article>)}</div><section className="meaning"><div><p className="eyebrow">MAKE MEANING</p><h2>Read scores as invitations to inquire.</h2><p>A lower implementation score is not a deficit label. Consider which strengths can be leveraged, whose perspectives may be missing, and what additional evidence the team needs.</p></div><div className="quad"><span>SUSTAIN<small>Higher implementation · lower priority</small></span><span>LEVERAGE<small>Higher implementation · higher priority</small></span><span>MONITOR<small>Lower implementation · lower priority</small></span><span>ACT<small>Lower implementation · higher priority</small></span></div></section><button className="reset" onClick={()=>{if(confirm("Clear all saved ratings on this device?")){setRatings({});setView("home")}}}><RotateCcw/>Start over</button></section>}
 <footer><div className="brand"><b>L</b><span>LEAP Innovations</span></div><p>Developmental reflection, not a readiness verdict.</p></footer></main>
}
